name: sarkisauto
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  flutter_bloc: ^8.1.1
  requests: ^4.5.0
  url_launcher: ^6.1.5
  flutter_rating_bar: ^4.0.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true
  assets:
    - lib/assets/
 
  fonts:
    - family: CustomIcons
      fonts:
        - asset: lib/assets/fonts/CustomIcons.ttf
    - family: Montserrat
      fonts:
        - asset: lib/assets/fonts/Montserrat-Regular.ttf
        - asset: lib/assets/fonts/Montserrat-Bold.ttf
        - asset: lib/assets/fonts/Montserrat-Regular.ttf
 